//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeSAPLogon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translatable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translatable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeSAPLogon.Translatable", typeof(Translatable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Logon.
        /// </summary>
        internal static string ButtonSAPLogonDlg {
            get {
                return ResourceManager.GetString("ButtonSAPLogonDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - config failure -.
        /// </summary>
        internal static string ColumnConfigFailure {
            get {
                return ResourceManager.GetString("ColumnConfigFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - invalid -.
        /// </summary>
        internal static string ColumnInvalidData {
            get {
                return ResourceManager.GetString("ColumnInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Logon.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string ColumnNoneSAPData {
            get {
                return ResourceManager.GetString("ColumnNoneSAPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one display option must be selected..
        /// </summary>
        internal static string ErrorMsgDisplayOption {
            get {
                return ResourceManager.GetString("ErrorMsgDisplayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to SAP GUI is not valid. Plugin runs auto detection..
        /// </summary>
        internal static string ErrorMsgSAPGUIPath {
            get {
                return ResourceManager.GetString("ErrorMsgSAPGUIPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Logon settings.
        /// </summary>
        internal static string TitelOptionDlg {
            get {
                return ResourceManager.GetString("TitelOptionDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected %EXE_NAME% - configuration is valid..
        /// </summary>
        internal static string ValidationInfoAuto {
            get {
                return ResourceManager.GetString("ValidationInfoAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not found %EXE_NAME% - configuration is not valid..
        /// </summary>
        internal static string ValidationInfoNeg {
            get {
                return ResourceManager.GetString("ValidationInfoNeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found %EXE_NAME% - configuration is valid..
        /// </summary>
        internal static string ValidationInfoPos {
            get {
                return ResourceManager.GetString("ValidationInfoPos", resourceCulture);
            }
        }
    }
}
